version: '3.9'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile.django
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  pgdata:
